# RabbitMQ Configuration File

# Memory settings
vm_memory_high_watermark.relative = 0.8

# Disk free space limit
disk_free_limit.absolute = 2GB

# log level
log.console.level = debug

# Hearth Beat Rate
heartbeat = 60